let num1 = 10;
let num2 = 5;
let soma = num1 + num2;
let sub = num1 - num2;
let mult = num1 * num2;
let div = num1 / num2;
let pot = num1 ^ num2;
console.log(`O resultado da soma entre 10 e 5 é ${soma}`);
console.log(`O resultado da subtração entre 10 e 5 é ${sub}`);
console.log(`O resultado da multiplicação entre 10 e 5 é ${mult}`);
console.log(`O resultado da divisão entre 10 e 5 é ${div}`);
console.log(`O resultado da potência entre 10 e 5 é ${pot}`);